name: 'Publish to GH pages'
description: ''
author: 'frontend@grafana'

inputs:
  grafana-image:
    description: 'Grafana image used in the test.'
    default: ${{ matrix.GRAFANA_IMAGE.NAME }}
    required: false
  grafana-version:
    description: 'Grafana version used in the test.'
    default: ${{ matrix.GRAFANA_IMAGE.VERSION }}
    required: false
  test-outcome:
    description: 'Outcome of the test step'
    required: true
  github-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
    required: false
    default: ${{ github.token }}
  upload-successful:
    description: 'Whether to upload the report if the test was successful.'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: rename report
      shell: bash
      run: |
        mv playwright-report ${{ inputs.grafana-image }}-v${{ inputs.grafana-version }}
        mkdir -p playwright-report
        mv ${{ inputs.grafana-image }}-v${{ inputs.grafana-version }} playwright-report/

    - name: remove successful report
      if: ${{ inputs.upload-successful == 'false' && inputs.test-outcome == 'success' }}
      shell: bash
      run: |
        rm -rf playwright-report/${{ inputs.grafana-image }}-v${{ inputs.grafana-version }}/*

    - name: Write test result to file
      shell: bash
      run: |
        SUMMARY="GRAFANA_IMAGE=${{ inputs.grafana-image }}
        GRAFANA_VERSION=${{ inputs.grafana-version }}
        OUTPUT=${{ inputs.test-outcome }}"

        echo "${SUMMARY}" > ./playwright-report/${{ inputs.grafana-image }}-v${{ inputs.grafana-version }}/summary.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ inputs.grafana-image }}-v${{ inputs.grafana-version }}
        path: playwright-report
        retention-days: 1